export const BASE_CATEGORY_KEYWORDS = {
  Музыка: [
    { word: 'живая музыка', value: 3 },
    { word: 'live music', value: 3 },
    { word: 'симфонический оркестр', value: 3 },
    { word: 'филармонический', value: 3 },
    { word: 'концерт', value: 2 },
    { word: 'concert', value: 2 },
    { word: 'Konzert', value: 2 },
    { word: 'оркестр', value: 2 },
    { word: 'orchestra', value: 2 },
    { word: 'филармония', value: 2 },
    { word: 'джаз', value: 2 },
    { word: 'jazz', value: 2 },
    { word: 'рок-концерт', value: 3 },
    { word: 'rock concert', value: 3 },
    { word: 'классическая музыка', value: 3 },
    { word: 'classical music', value: 3 },
    { word: 'электронная музыка', value: 2 },
    { word: 'electronic music', value: 2 },
    { word: 'группа', value: 1 },
    { word: 'band', value: 1 },
    { word: 'исполнитель', value: 1 },
    { word: 'певец', value: 1 },
    { word: 'певица', value: 1 },
    { word: 'singer', value: 1 },
    { word: 'рок', value: 1 },
    { word: 'rock', value: 1 },
    { word: 'поп', value: 1 },
    { word: 'pop', value: 1 },
    { word: 'hip-hop', value: 1 },
    { word: 'hip hop', value: 1 },
    { word: 'rap', value: 1 },
    { word: 'рэп', value: 1 },
    { word: 'DJ', value: 1 },
    { word: 'диджей', value: 1 },
    { word: 'gig', value: 1 },
    { word: 'music', value: 1 },
    { word: 'Musik', value: 1 },
    { word: 'музыка', value: 1 },
    { word: 'опера', value: 2 },
    { word: 'opera', value: 2 },
    { word: 'хор', value: 1 },
    { word: 'choir', value: 1 },
    { word: 'акустика', value: 1 },
    { word: 'acoustic', value: 1 },
    { word: 'блюз', value: 1 },
    { word: 'blues', value: 1 },
    { word: 'metal', value: 1 },
    { word: 'метал', value: 1 },
    { word: 'indie', value: 1 },
    { word: 'folk', value: 1 },
    { word: 'фолк', value: 1 },
  ],
  Театр: [
    { word: 'театральная постановка', value: 3 },
    { word: 'theatre performance', value: 3 },
    { word: 'theater performance', value: 3 },
    { word: 'драматический спектакль', value: 3 },
    { word: 'спектакль', value: 2 },
    { word: 'постановка', value: 2 },
    { word: 'пьеса', value: 2 },
    { word: 'театр', value: 2 },
    { word: 'theatre', value: 2 },
    { word: 'theater', value: 2 },
    { word: 'Theater', value: 2 },
    { word: 'Schauspiel', value: 2 },
    { word: 'драма', value: 1 },
    { word: 'drama', value: 1 },
    { word: 'комедия', value: 1 },
    { word: 'актёр', value: 1 },
    { word: 'актер', value: 1 },
    { word: 'actress', value: 1 },
    { word: 'actor', value: 1 },
    { word: 'сцена', value: 1 },
    { word: 'stage play', value: 2 },
    { word: 'трагедия', value: 1 },
    { word: 'репертуар', value: 1 },
    { word: 'иммерсивный театр', value: 3 },
    { word: 'puppet', value: 1 },
    { word: 'кукольный', value: 2 },
  ],
  'Шоу/Мюзиклы': [
    { word: 'мюзикл', value: 3 },
    { word: 'musical', value: 3 },
    { word: 'Musical', value: 3 },
    { word: 'broadway', value: 3 },
    { word: 'Broadway', value: 3 },
    { word: 'variety show', value: 3 },
    { word: 'варьете', value: 2 },
    { word: 'цирковое шоу', value: 3 },
    { word: 'circus show', value: 3 },
    { word: 'иллюзион', value: 2 },
    { word: 'magic show', value: 3 },
    { word: 'шоу', value: 1 },
    { word: 'show', value: 1 },
    { word: 'cabaret', value: 2 },
    { word: 'кабаре', value: 2 },
    { word: 'revue', value: 2 },
    { word: 'ледовое шоу', value: 3 },
    { word: 'ice show', value: 3 },
    { word: 'импровизационное шоу', value: 2 },
  ],
  Юмор: [
    { word: 'stand-up comedy', value: 3 },
    { word: 'stand up comedy', value: 3 },
    { word: 'стендап', value: 3 },
    { word: 'stand-up', value: 2 },
    { word: 'stand up', value: 2 },
    { word: 'comedy club', value: 3 },
    { word: 'юмористический концерт', value: 3 },
    { word: 'комик', value: 2 },
    { word: 'comedian', value: 2 },
    { word: 'юмор', value: 2 },
    { word: 'гумор', value: 2 },
    { word: 'comedy', value: 2 },
    { word: 'Kabarett', value: 2 },
    { word: 'сатира', value: 2 },
    { word: 'satire', value: 2 },
    { word: 'импровизация', value: 1 },
    { word: 'improv', value: 1 },
    { word: 'open mic', value: 2 },
    { word: 'открытый микрофон', value: 2 },
  ],
  Фестивали: [
    { word: 'музыкальный фестиваль', value: 3 },
    { word: 'music festival', value: 3 },
    { word: 'open-air festival', value: 3 },
    { word: 'open air', value: 2 },
    { word: 'open-air', value: 2 },
    { word: 'фестиваль', value: 2 },
    { word: 'festival', value: 2 },
    { word: 'Stadtfest', value: 2 },
    { word: 'street festival', value: 2 },
    { word: 'уличный фестиваль', value: 2 },
    { word: 'фольклорный фестиваль', value: 3 },
    { word: 'food festival', value: 2 },
    { word: 'гастрономический фестиваль', value: 2 },
    { word: 'film festival', value: 2 },
    { word: 'кинофестиваль', value: 2 },
  ],
  Семейное: [
    { word: 'для всей семьи', value: 3 },
    { word: 'family friendly', value: 3 },
    { word: 'семейное мероприятие', value: 3 },
    { word: 'для детей', value: 2 },
    { word: 'детский', value: 2 },
    { word: 'kids', value: 2 },
    { word: 'children', value: 2 },
    { word: 'family', value: 1 },
    { word: 'Familie', value: 1 },
    { word: 'Kinder', value: 1 },
    { word: 'семейное', value: 2 },
    { word: 'дети', value: 1 },
    { word: 'анимация для детей', value: 3 },
    { word: 'детский праздник', value: 3 },
    { word: 'сказки', value: 1 },
  ],
  Искусство: [
    { word: 'contemporary art', value: 3 },
    { word: 'современное искусство', value: 3 },
    { word: 'art gallery', value: 3 },
    { word: 'художественная галерея', value: 3 },
    { word: 'живопись', value: 2 },
    { word: 'скульптура', value: 2 },
    { word: 'sculpture', value: 2 },
    { word: 'painting', value: 2 },
    { word: 'галерея', value: 2 },
    { word: 'Galerie', value: 2 },
    { word: 'искусство', value: 1 },
    { word: 'art', value: 1 },
    { word: 'Kunst', value: 1 },
    { word: 'арт', value: 1 },
    { word: 'инсталляция', value: 2 },
    { word: 'installation art', value: 2 },
    { word: 'фотовыставка', value: 2 },
    { word: 'photography exhibition', value: 2 },
  ],
  Духовное: [
    { word: 'медитация', value: 2 },
    { word: 'meditation', value: 2 },
    { word: 'йога', value: 2 },
    { word: 'yoga', value: 2 },
    { word: 'духовное', value: 2 },
    { word: 'spiritual', value: 2 },
    { word: 'ретрит', value: 2 },
    { word: 'retreat', value: 2 },
    { word: 'молитва', value: 1 },
    { word: 'религиозн', value: 1 },
    { word: 'mindfulness', value: 2 },
    { word: 'осознанность', value: 2 },
    { word: 'духовная практика', value: 3 },
  ],
  Спорт: [
    { word: 'футбольный матч', value: 3 },
    { word: 'football match', value: 3 },
    { word: 'soccer match', value: 3 },
    { word: 'чемпионат', value: 2 },
    { word: 'championship', value: 2 },
    { word: 'турнир', value: 2 },
    { word: 'tournament', value: 2 },
    { word: 'матч', value: 2 },
    { word: 'match', value: 1 },
    { word: 'спорт', value: 1 },
    { word: 'sport', value: 1 },
    { word: 'Sports', value: 1 },
    { word: 'Sportveranstaltung', value: 2 },
    { word: 'хоккей', value: 2 },
    { word: 'hockey', value: 2 },
    { word: 'баскетбол', value: 2 },
    { word: 'basketball', value: 2 },
    { word: 'теннис', value: 2 },
    { word: 'tennis', value: 2 },
    { word: 'марафон', value: 2 },
    { word: 'marathon', value: 2 },
    { word: 'бег', value: 1 },
    { word: 'running', value: 1 },
    { word: 'единоборства', value: 2 },
    { word: 'boxing', value: 2 },
    { word: 'бокс', value: 2 },
    { word: 'MMA', value: 2 },
    { word: 'формула', value: 1 },
    { word: 'Formula', value: 1 },
  ],
  Выставки: [
    { word: 'выставка', value: 2 },
    { word: 'exhibition', value: 2 },
    { word: 'Ausstellung', value: 2 },
    { word: 'экспозиция', value: 2 },
    { word: 'музей', value: 2 },
    { word: 'museum', value: 2 },
    { word: 'Museum', value: 2 },
    { word: 'expo', value: 1 },
    { word: 'ярмарка', value: 1 },
    { word: 'fair', value: 1 },
    { word: 'trade show', value: 2 },
    { word: 'автосалон', value: 2 },
    { word: 'книжная ярмарка', value: 2 },
    { word: 'book fair', value: 2 },
  ],
  Танцы: [
    { word: 'балет', value: 3 },
    { word: 'ballet', value: 3 },
    { word: 'танцевальный спектакль', value: 3 },
    { word: 'dance performance', value: 3 },
    { word: 'хореография', value: 2 },
    { word: 'choreography', value: 2 },
    { word: 'танцы', value: 2 },
    { word: 'dance', value: 1 },
    { word: 'Tanz', value: 1 },
    { word: 'salsa', value: 2 },
    { word: 'bachata', value: 2 },
    { word: 'tango', value: 2 },
    { word: 'танго', value: 2 },
    { word: 'hip-hop dance', value: 2 },
    { word: 'contemporary dance', value: 2 },
    { word: 'современный танец', value: 2 },
    { word: 'ballroom', value: 2 },
    { word: 'бальные танцы', value: 2 },
  ],
  'Лекции/Семинары': [
    { word: 'мастер-класс', value: 3 },
    { word: 'master class', value: 3 },
    { word: 'masterclass', value: 3 },
    { word: 'лекция', value: 2 },
    { word: 'lecture', value: 2 },
    { word: 'Vortrag', value: 2 },
    { word: 'семинар', value: 2 },
    { word: 'seminar', value: 2 },
    { word: 'workshop', value: 2 },
    { word: 'воркшоп', value: 2 },
    { word: 'конференция', value: 2 },
    { word: 'conference', value: 2 },
    { word: 'тренинг', value: 2 },
    { word: 'training', value: 1 },
    { word: 'вебинар', value: 1 },
    { word: 'панельная дискуссия', value: 2 },
    { word: 'panel discussion', value: 2 },
    { word: 'meetup', value: 1 },
  ],
};

export default BASE_CATEGORY_KEYWORDS;
